version: "3"
services:
  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=bookstore
      - POSTGRES_USER=bookstore
      - POSTGRES_DB=bookstore